### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by zeptometer** [nyuichi/satysfi-base#251]
# TODOs
For detailed steps, refer to [素敵なライブラリをSatyrographosで配布しよう！](https://qiita.com/na4zagin3/items/b392f5d522f9bcc0493b).

* [x] Update opam and Satyristes → https://github.com/nyuichi/satysfi-base/pull/257
* [x] Crete tag 1.5.0
* [x] Create PR to satyrographos repo
* [ ] Get the PR merged

**Comment by zeptometer** [comment]
Considering a few features have been added, the new version should be 1.5.0. Updating the issue title.

**Comment by zeptometer** [comment]
Here is the PR to satyrographos-repo 👉  https://github.com/na4zagin3/satyrographos-repo/pull/500
