### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by zeptometer** [nyuichi/satysfi-base#281]
# TODOs
For detailed steps, refer to [素敵なライブラリをSatyrographosで配布しよう！](https://qiita.com/na4zagin3/items/b392f5d522f9bcc0493b).

* [ ] Update opam and Satyristes → https://github.com/nyuichi/satysfi-base/pull/257
* [ ] Crete tag 1.6.0
* [ ] Create PR to satyrographos repo
* [ ] Get the PR merged
